### ISSUE TITLE
Haal hier ook de websites van de API op

### ISSUE THREAD

**Issue by KrijnHoetmer** [amirdev98/the-web-is-for-everyone-interactive-functionality#1]
Kijk bijvoorbeeld bij Celine, Cathelijne of Tim voor wat oplossingen.

https://github.com/amirdev98/the-web-is-for-everyone-interactive-functionality/blob/c2d8098577f1191964df65efcfcb4e62a3680ef3/index.js#L30-L35

**Comment by amirnapoletano** [comment]
Dankjewel Krijn!
